services:
  backend:
    image: ${IMAGE_REGISTRY:-your-dockerhub-username}/kuba-backend:${IMAGE_TAG:-latest}
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - backend-data:/app/data
    networks:
      - app

  public-frontend:
    image: ${IMAGE_REGISTRY:-your-dockerhub-username}/kuba-public:${IMAGE_TAG:-latest}
    restart: unless-stopped
    networks:
      - app

  display-frontend:
    image: ${IMAGE_REGISTRY:-your-dockerhub-username}/kuba-display:${IMAGE_TAG:-latest}
    restart: unless-stopped
    networks:
      - app

  admin-frontend:
    image: ${IMAGE_REGISTRY:-your-dockerhub-username}/kuba-admin:${IMAGE_TAG:-latest}
    restart: unless-stopped
    networks:
      - app

  audio-frontend:
    image: ${IMAGE_REGISTRY:-your-dockerhub-username}/kuba-audio:${IMAGE_TAG:-latest}
    restart: unless-stopped
    networks:
      - app

  plausible-db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${PLAUSIBLE_DB_NAME:-plausible}
      - POSTGRES_USER=${PLAUSIBLE_DB_USER:-plausible}
      - POSTGRES_PASSWORD=${PLAUSIBLE_DB_PASSWORD:-plausible}
    volumes:
      - plausible-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PLAUSIBLE_DB_USER:-plausible} -d ${PLAUSIBLE_DB_NAME:-plausible}"]
      start_period: 1m
    networks:
      - app

  plausible-events-db:
    image: clickhouse/clickhouse-server:24.12-alpine
    restart: unless-stopped
    environment:
      - CLICKHOUSE_SKIP_USER_SETUP=1
    volumes:
      - plausible-event-data:/var/lib/clickhouse
      - plausible-event-logs:/var/log/clickhouse-server
      - ./plausible-ce/clickhouse/logs.xml:/etc/clickhouse-server/config.d/logs.xml:ro
      - ./plausible-ce/clickhouse/ipv4-only.xml:/etc/clickhouse-server/config.d/ipv4-only.xml:ro
      - ./plausible-ce/clickhouse/low-resources.xml:/etc/clickhouse-server/config.d/low-resources.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 -O - http://127.0.0.1:8123/ping || exit 1"]
      start_period: 1m
    networks:
      - app

  plausible:
    image: ghcr.io/plausible/community-edition:v3.0.1
    restart: unless-stopped
    depends_on:
      plausible-db:
        condition: service_healthy
      plausible-events-db:
        condition: service_healthy
    environment:
      - BASE_URL=${PLAUSIBLE_BASE_URL}
      - SECRET_KEY_BASE=${PLAUSIBLE_SECRET_KEY_BASE}
      - DATABASE_URL=ecto://${PLAUSIBLE_DB_USER:-plausible}:${PLAUSIBLE_DB_PASSWORD:-plausible}@plausible-db:5432/${PLAUSIBLE_DB_NAME:-plausible}
      - CLICKHOUSE_DATABASE_URL=http://plausible-events-db:8123/${PLAUSIBLE_CLICKHOUSE_DB:-plausible}
      - HTTP_PORT=8000
      - HTTPS_PORT=8443
      - DISABLE_REGISTRATION=${PLAUSIBLE_DISABLE_REGISTRATION:-true}
      - MAILER_ADAPTER=${PLAUSIBLE_MAILER_ADAPTER:-Bamboo.LocalAdapter}
      - MAILER_EMAIL=${PLAUSIBLE_MAILER_EMAIL:-noreply@kunstradbasketball.de}
      - MAILER_NAME=${PLAUSIBLE_MAILER_NAME:-Kuba Manager Analytics}
    volumes:
      - plausible-app-data:/var/lib/plausible
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - app

  caddy:
    image: caddy:2.8-alpine
    restart: unless-stopped
    depends_on:
      - backend
      - public-frontend
      - display-frontend
      - admin-frontend
      - audio-frontend
      - plausible
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "3000:3000"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  backend-data:
  caddy_data:
  caddy_config:
  plausible-db-data:
  plausible-event-data:
  plausible-event-logs:
  plausible-app-data:
